export const ACTION_TEST = 'ACTION_TEST'
export const START = 'START'
export const ADD_TIMER ='ADD_TIMER'
export const FINISH_TIMER = 'FINISH_TIMER'
export const GET_ALL_VEHICLES = 'GET_ALL_VEHICLES'
export const CREATE_VEHICLE = 'CREATE_VEHICLE'
export const API_URL = 'http://localhost:8081'